### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ghost** [nullstalgia/UARTSwitchCon#3]
....

**Comment by nullstalgia** [comment]
Ah, the issue is that you're flashing a binary meant for an ATMega32U4 (Arduino Pro Micro and clones) onto a 16U2. Kinda like trying to run a x86 Windows app on a x86 Linux machine, similar base hardware but they expect different things.

If you need, I can see if I can compile this for a 16U2. Been a while since I've had to do so, so it may take me a little bit.

**Comment by Uniersr** [comment]
Yes i need it.

**Comment by nullstalgia** [comment]
[UARTSwitchCon-Uno16u2.zip](https://github.com/nullstalgia/UARTSwitchCon/files/8405852/UARTSwitchCon-Uno16u2.zip)

Try this, it worked on my board. I recommend also downloading the release of my [ClubchatGames](https://github.com/nullstalgia/ClubchatGames/releases/tag/1.0) as it provides a manual control interface for the UARTSwitchCon, which is helpful when testing. :)

![image](https://user-images.githubusercontent.com/20761757/161454475-91a87ed7-94de-4fde-85d1-afb12317e0a6.png)

**Comment by Uniersr** [comment]
When i plugged my blue cable to my PC it recognizes as UARTSwitchCon but it acts as Horipad S so i disconnected my blue cable to my pc then i connected to my nintendo switch, when i try to connect using [ClubchatGames](https://github.com/nullstalgia/ClubchatGames/releases/tag/1.0), my serial adapter turns on both TXD and RXD for a little while then it turns off then TXD and RXD on serial adapter blinks 2 or 3 times for like 2 to 5 seconds each then after, [ClubchatGames](https://github.com/nullstalgia/ClubchatGames/releases/tag/1.0) says FAIL, certainly because my arduino doesn't have UART1 but only have TX and RX on right-upper corner of the arduino, i think it's a issue.
![image](https://user-images.githubusercontent.com/99698024/161572435-7599a2f7-06b3-4cd0-83ef-3cba3df41447.png)
![image](https://user-images.githubusercontent.com/99698024/161573558-f4a3930a-dcc3-4c42-a223-bf8778a2ada0.png)

**Comment by nullstalgia** [comment]
I'd add a GND wire connecting the Serial board's GND to the Arduino's GND. Also try Swapping the TX and RX wires on the Arduino side only and see if that works. 

I tested it by using those same ports on my Arduino UNO, so I'd expect it should work on yours as well with a little work.

**Comment by Uniersr** [comment]
> I'd add a GND wire connecting the Serial board's GND to the Arduino's GND. Also try Swapping the TX and RX wires on the Arduino side only and see if that works.

Flashed UARTSwitchCon-Uno16u2.hex one more time, Tried with GND and 5V, not working......
When i disconnect all of them from my pc and nintendo switch then i connect my arduino from blue cable to my pc, it's recognized as UARTSwitchCon, so do i need to install HoodLoader2 to my arduino?
![image](https://user-images.githubusercontent.com/99698024/162235295-de0b16f6-001f-4ab3-83fc-a03b92ea6a16.png)

**Comment by Uniersr** [comment]
@nullstalgia i would have closed the issue now since https://github.com/Kashalls/NintendoSwitchController fixed the issue for me.

https://user-images.githubusercontent.com/99698024/190917297-e28b364c-1be8-475f-a8fd-012c6c4ec26b.mp4

**Comment by nullstalgia** [comment]
Are you using an ATMega32U4 now? Or still the same board?

**Comment by Uniersr** [comment]
> Are you using an ATMega32U4 now? Or still the same board?

@nullstalgia Still the same board, yesterday, i just changed the MCU value to atmega16u2 in makefile from NintendoSwitchController but today i moved on to javmarina's Nintendo-Switch-Remote-Control then compiled the Joystick.hex with only modification to 115200 baudrate then flashed both atmega328p and atmega16u2 from the same board and i was able to connect it without issues, the issue from Mar 28 2022 was that i forgot to flash Joystick.hex to atmega328p and it's now fixed today. 

![image](https://user-images.githubusercontent.com/99698024/191051701-0402f711-0937-4fc1-b2b4-6496514b1913.png)
